name: Continuous Integration Test
on:
    workflow_dispatch:
    schedule:
        - cron: '0 1 * * 0'
jobs:
    ci_test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              shell: bash
              working-directory: ${{runner.workspace}}
              run: git clone https://github.com/ORNL-Fusion/Stellarator-Tools.git ${{runner.workspace}}/Stellarator-Tools
            - name: Checkout Branch
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/
              run: git checkout master_dev
            - name: Create build directory.
              run: cmake -E make_directory ${{runner.workspace}}/Stellarator-Tools/build
            - name: Install Libraries
              shell: bash
              run: |
                sudo apt update
                sudo apt-get install libnetcdf-dev
                sudo apt-get install libnetcdff-dev
                sudo apt-get install libopenmpi-dev
                sudo apt-get install libscalapack-openmpi-dev
            - name: Configure CMake
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_DEBUG_FLAGS="-ffpe-trap=denormal -fsanitize=address" -DBUILD_V3FIT=ON -DBUILD_V3RFUN=ON -DBUILD_SIESTA=ON -DBUILD_LGRID=ON -DBUILD_SURFACE=ON -DBUILD_BMW=ON -DBUILD_PARVMEC=ON -DBUILD_DESCUR=ON -DBUILD_TAG_V3FIT=master_dev -DBUILD_TAG_V3RFUN=master_dev -DBUILD_TAG_SIESTA=master_dev -DBUILD_TAG_LGRID=master_dev -DBUILD_TAG_SURFACE=master_dev -DBUILD_TAG_BMW=master_dev -DBUILD_TAG_LIBSTELL=master_dev -DBUILD_TAG_MAKEGRID=master_dev -DBUILD_TAG_PARVMEC=master_dev -DBUILD_TAG_DESCUR=master_dev -DUSE_FAST_COPY=ON -DUSE_PROFILER=ON ${{runner.workspace}}/Stellarator-Tools/
            - name: Build
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: make VERBOSE=1
            - name: Test
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: make test
            - name: Show Log
              if: failure()
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build/Testing/Temporary
              run: cat LastTest.log
