name: Continous Integration Test
on:
    workflow_dispatch:
jobs:
    ci_test:
        runs-on: ubuntu-latest
        steps:
#            - uses: actions/checkout@master_dev
            - name: Show current directory.
              shell: bash
              working-directory: ${{runner.workspace}}
              run: ls
            - name: Create build directory.
              run: cmake -E make_directory ${{runner.workspace}}/build
            - name: Configure CMake
              shell: bash
              working-directory: ${{runner.workspace}}/build
              run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE=Release -DBUILD_MAKEGRID=ON -DBUILD_TAG_LIBSTELL=master_dev -DBUILD_TAG_MAKEGRID=master_dev -USE_FAST_COPY=ON -DUSE_PROFILER=ON $GITHUB_WORKSPACE
            - name: Build
              shell: bash
              working-directory: ${{runner.workspace}}/build
              run: make
            - name: Test
              shell: bash
              working-directory: ${{runner.workspace}}/build
              run: make test
