name: Continuous Integration Test
on:
    workflow_dispatch:
jobs:
    ci_test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              shell: bash
              working-directory: ${{runner.workspace}}
              run: git clone https://github.com/ORNL-Fusion/Stellarator-Tools.git ${{runner.workspace}}/Stellarator-Tools
            - name: Checkout Branch
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/
              run: git checkout master_dev
            - name: Create build directory.
              run: cmake -E make_directory ${{runner.workspace}}/Stellarator-Tools/build
            - name: Install Libraries
              shell: bash
              run: |
                sudo apt-get install libnetcdf-dev
                sudo apt-get install libnetcdff-dev
                sudo apt-get install libopenmpi-dev
            - name: Configure CMake
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE=Release -DBUILD_MAKEGRID=ON -DBUILD_TAG_LIBSTELL=master_dev -DBUILD_TAG_MAKEGRID=master_dev -DUSE_FAST_COPY=ON -DUSE_PROFILER=ON ${{runner.workspace}}/Stellarator-Tools/
            - name: Build
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: make VERBOSE=1
            - name: Test
              shell: bash
              working-directory: ${{runner.workspace}}/Stellarator-Tools/build
              run: make test
